export DOTFILES="${HOME}/dotfiles"

: ${XDG_CACHE_HOME:=${HOME}/.cache}        # non-essential cached data
: ${XDG_CONFIG_HOME:=${HOME}/.config}      # user-specific portable configuration
: ${XDG_DATA_HOME:=${HOME}/.local/share}   # user-specific data (venvs, nvim swap)
: ${XDG_STATE_HOME:=${HOME}/.local/state}  # persistent app state (logs, history)
export XDG_CACHE_HOME XDG_CONFIG_HOME XDG_DATA_HOME XDG_STATE_HOME

# Shell histories
export HISTFILE="${XDG_STATE_HOME}/zsh/history"
export HISTFILE_BASH="${XDG_STATE_HOME}/bash/history"  # see note below
export LESSHISTFILE="${XDG_STATE_HOME}/less/history"

# inputrc for bash's readline
export INPUTRC="$XDG_CONFIG_HOME"/readline/inputrc

# macOS Terminal "Resume" feature (which I don't use)
export SHELL_SESSIONS_DISABLE=1   # if you don't use them; or:
# export SHELL_SESSION_DIR="${XDG_STATE_HOME}/zsh/sessions"

# Python REPL (3.13+)
export PYTHON_HISTORY="${XDG_STATE_HOME}/python/history"

# Node REPL
export NODE_REPL_HISTORY="${XDG_STATE_HOME}/node/repl_history"

# psql
export PSQL_HISTORY="${XDG_STATE_HOME}/psql/history"

# npm
export NPM_CONFIG_USERCONFIG="${XDG_CONFIG_HOME}/npm/npmrc"
export NPM_CONFIG_CACHE="${XDG_CACHE_HOME}/npm"
export NPM_CONFIG_INIT_MODULE="${XDG_CONFIG_HOME}/npm/config/npm-init.js"
export NPM_CONFIG_LOGS_DIR="${XDG_STATE_HOME}/npm/logs"

# rustup / cargo
export RUSTUP_HOME="${XDG_DATA_HOME}/rustup"
export CARGO_HOME="${XDG_DATA_HOME}/cargo"

# go
export GOPATH="$XDG_DATA_HOME"/go

# Julia
export JULIA_DEPOT_PATH="${XDG_DATA_HOME}/julia:${JULIA_DEPOT_PATH}"

# R
export R_HISTFILE="${XDG_STATE_HOME}/r/history"
export R_PROFILE_USER="${XDG_CONFIG_HOME}/r/Rprofile"  # since you symlink .Rprofile already
export R_LIBS_USER="${XDG_DATA_HOME}/r/library"

# Docker
export DOCKER_CONFIG="${XDG_CONFIG_HOME}/docker"
